// src/Data.js
export const dataSlider1 = [
  {
    id: 1,
    image: './slider1.webp',
    alt: 'picSlider1',
    title: 'فرش کهن دست بافت سهند زمینه سرمه ای',
    price: '۲۳۳,۰۰۰ تومان',
    delay: 0.3,
  },
  {
    id: 2,
    image: './slider2.webp',
    alt: 'picSlider2',
    title: 'فرش دست بافت زانیس ماربل زمینه نوک مدادی',
    price: '۴۹,۹۲۰ تومان',
    delay: 0.6,
  },
  {
    id: 3,
    image: './slider3.webp',
    alt: 'picSlider3',
    title: 'فرش دست بافت نگین مشهد زمینه فیلی',
    price: '۱۴,۵۰۰,۰۰۰ تومان',
    delay: 0.9,
  },
  {
    id: 4,
    image: './slider4.webp',
    alt: 'picSlider4',
    title: 'فرش دست بافت سهندآترینا زمینه سورمه ای',
    price: '۲۳۳,۰۰۰ تومان',
    delay: 1.2,
  },
];

export const dataSlider2 = [
  {
    id: 1,
    image: './slider5.webp',
    alt: 'picSlider5',
    title: 'فرش ماشینی ماهساره طرح آترینا زمینه آبی',
    price: '۱۳,۵۰۰,۰۰۰ تومان',
    delay: 0.3,
  },
  {
    id: 2,
    image: './slider6.webp',
    alt: 'picSlider6',
    title: 'فرش ماشینی لوکس سهند زمینه سرمه ای ',
    price: '۲۳۳,۰۰۰ تومان',
    delay: 0.6,
  },
  {
    id: 3,
    image: './slider7.webp',
    alt: 'picSlider7',
    title: 'فرش ماشینی رادین طرح شاه عباسی زمینه کرم',
    price: '۶,۳۰۳,۰۰۰ تومان',
    delay: 0.9,
  },
  {
    id: 4,
    image: './slider8.webp',
    alt: 'picSlider8',
    title: 'فرش ماشینی مشهد طرح افشان زمینه کرم ',
    price: '۱۱,۶۰۰,۰۰۰ تومان',
    delay: 1.2,
  },
];

export const dataSlider3 = [
  {
    id: 1,
    image: './slider6.webp',
    alt: 'picSlider6',
    title: 'فرش ماشینی لوکس سهند زمینه سرمه ای ',
    price: '۲۳۳,۰۰۰ تومان',
    delay: 0.6,
  },
  {
    id: 2,
    image: './slider9.webp',
    alt: 'picSlider9',
    title: 'فرش کهن  دست بافت سهند زمینه سرمه ای ',
    price: '۲۳۳,۰۰۰ تومان',
    delay: 0.6,
  },
  {
    id: 3,
    image: './slider7.webp',
    alt: 'picSlider7',
    title: 'فرش ماشینی رادین طرح شاه عباسی زمینه کرم',
    price: '۶,۳۰۳,۰۰۰ تومان',
    delay: 0.9,
  },
  {
    id: 4,
    image: './slider8.webp',
    alt: 'picSlider8',
    title: 'فرش ماشینی مشهد طرح افشان زمینه کرم ',
    price: '۱۱,۶۰۰,۰۰۰ تومان',
    delay: 1.2,
  },
  {
    id: 5,
    image: './slider10.webp',
    alt: 'picSlider10',
    title: 'فرش ماشینی ماهساره طرح آترینا ',
    price: '۱۳,۵۰۰,۰۰۰ تومان',
    delay: 0.3,
  },
];

export const NavLinks = [
  {
    id: 1,
    name: 'صفحه اصلی',
    href: '/',
  },
  {
    id: 2,
    name: 'فرش های سه بعدی',
    href: '/3dmodels',
  },
  {
    id: 3,
    name: 'وبلاگ',
    href: '/blog',
  },
  {
    id: 4,
    name: 'تماس با ما',
    href: '/contactus',
  },
  {
    id: 5,
    name: 'درباره ما',
    href: '/about',
  },
];

export const models3D = [
  {
    title: 'فرش سه بعدی آبی',
    desc: 'با الهام از نقوش معرق کاشی‌کاری ایرانی، این فرش سه‌بعدی با رنگ‌های آرامش‌بخش فیروزه‌ای و طراحی متقارن، زیبایی خیره‌کننده‌ای به فضای شما می‌بخشد. مناسب سبک‌های مدرن و سنتی با نور ملایم.',
    price: '۱۲,۵۰۰,۰۰۰',
    path: '/model5.glb',
  },
  {
    title: 'فرش سه‌ بعدی قرمز',
    desc: 'این فرش سه‌بعدی با طرح اصیل ترنج و زمینه‌ی قرمز غنی، نمادی از شکوه فرش‌های سنتی ایرانی است. جزئیات دقیق و بافت سه‌بعدی آن، جلوه‌ای زنده و واقعی به دکوراسیون شما می‌دهد.',
    price: '۹,۸۰۰,۰۰۰',
    path: '/model2.glb',
  },
  {
    title: 'فرش سه ‌بعدی فیروزه ای',
    desc: 'طراحی این فرش با رنگ‌های محو و ظاهر کهنه‌نما، حس اصالت و خاطره را به فضای شما می‌آورد. مناسب فضاهای هنری، کافه‌ها، یا خانه‌هایی با حال‌و‌هوای نوستالژیک برای دکوراسیون شماست.',
    price: '۱۵,۰۰۰,۰۰۰',
    path: '/model3.glb',
  },
];

export const ProductData = [
  {
    id: 1,
    title: 'فرش ابریشمی تبریز',
    price: 12500000,
    category: 'ابریشمی',
    image: '/slider1.webp',
  },
  {
    id: 2,
    title: 'فرش ماشینی 1200 شانه',
    price: 8200000,
    category: 'ماشینی',
    image: '/slider2.webp',
  },
  {
    id: 3,
    title: 'فرش دستباف کاشان',
    price: 20000000,
    category: 'دستباف',
    image: '/slider3.webp',
  },
  {
    id: 4,
    title: 'فرش فانتزی مدرن',
    price: 5500000,
    category: 'مدرن',
    image: '/slider4.webp',
  },
  {
    id: 5,
    title: 'فرش کلاسیک 700 شانه',
    price: 6400000,
    category: 'ماشینی',
    image: '/slider5.webp',
  },
  {
    id: 6,
    title: 'فرش گل برجسته اصفهان',
    price: 9800000,
    category: 'ابریشمی',
    image: '/slider6.webp',
  },
  {
    id: 7,
    title: 'فرش سنتی ترکمن',
    price: 14500000,
    category: 'دستباف',
    image: '/slider7.webp',
  },
  {
    id: 8,
    title: 'فرش فانتزی کودک',
    price: 3900000,
    category: 'مدرن',
    image: '/slider8.webp',
  },
  {
    id: 9,
    title: 'فرش ماشینی ارزان',
    price: 2700000,
    category: 'ماشینی',
    image: '/slider9.webp',
  },
  {
    id: 10,
    title: 'فرش ابریشمی نایین',
    price: 14800000,
    category: 'ابریشمی',
    image: '/images/carpet10.jpg',
  },
  {
    id: 11,
    title: 'فرش ماشینی گل برجسته',
    price: 9100000,
    category: 'ماشینی',
    image: '/images/carpet11.jpg',
  },
  {
    id: 12,
    title: 'فرش دستباف مشهد',
    price: 17500000,
    category: 'دستباف',
    image: '/images/carpet12.jpg',
  },
  {
    id: 13,
    title: 'فرش مدرن هندسی',
    price: 4700000,
    category: 'مدرن',
    image: '/images/carpet13.jpg',
  },
  {
    id: 14,
    title: 'فرش ماشینی طرح افشان',
    price: 6900000,
    category: 'ماشینی',
    image: '/images/carpet14.jpg',
  },
  {
    id: 15,
    title: 'فرش ابریشمی قم',
    price: 16200000,
    category: 'ابریشمی',
    image: '/images/carpet15.jpg',
  },
  {
    id: 16,
    title: 'فرش دستباف تبریز اصیل',
    price: 21000000,
    category: 'دستباف',
    image: '/images/carpet16.jpg',
  },
  {
    id: 17,
    title: 'فرش مدرن فانتزی رنگی',
    price: 5200000,
    category: 'مدرن',
    image: '/images/carpet17.jpg',
  },
  {
    id: 18,
    title: 'فرش ماشینی ترک طرح جدید',
    price: 8600000,
    category: 'ماشینی',
    image: '/images/carpet18.jpg',
  },
  {
    id: 19,
    title: 'فرش ابریشمی برجسته',
    price: 13500000,
    category: 'ابریشمی',
    image: '/images/carpet19.jpg',
  },
  {
    id: 20,
    title: 'فرش دستباف بلوچ',
    price: 18900000,
    category: 'دستباف',
    image: '/images/carpet20.jpg',
  },
  {
    id: 21,
    title: 'فرش کودک طرح خرس',
    price: 3100000,
    category: 'مدرن',
    image: '/images/carpet21.jpg',
  },
  {
    id: 22,
    title: 'فرش ماشینی کلاسیک',
    price: 7300000,
    category: 'ماشینی',
    image: '/images/carpet22.jpg',
  },
  {
    id: 23,
    title: 'فرش ابریشمی کاشان',
    price: 15800000,
    category: 'ابریشمی',
    image: '/images/carpet23.jpg',
  },
  {
    id: 24,
    title: 'فرش دستباف هریس',
    price: 19400000,
    category: 'دستباف',
    image: '/images/carpet24.jpg',
  },
  {
    id: 25,
    title: 'فرش مدرن مینیمال',
    price: 4800000,
    category: 'مدرن',
    image: '/images/carpet25.jpg',
  },
  {
    id: 26,
    title: 'فرش ماشینی طرح خشتی',
    price: 7800000,
    category: 'ماشینی',
    image: '/images/carpet26.jpg',
  },
  {
    id: 27,
    title: 'فرش ابریشمی گل ابریشم',
    price: 14300000,
    category: 'ابریشمی',
    image: '/images/carpet27.jpg',
  },
  {
    id: 28,
    title: 'فرش دستباف سنندج',
    price: 17200000,
    category: 'دستباف',
    image: '/images/carpet28.jpg',
  },
  {
    id: 29,
    title: 'فرش فانتزی ساده طوسی',
    price: 4500000,
    category: 'مدرن',
    image: '/images/carpet29.jpg',
  },
  {
    id: 30,
    title: 'فرش ماشینی گلریز',
    price: 6950000,
    category: 'ماشینی',
    image: '/images/carpet30.jpg',
  },
  {
    id: 31,
    title: 'فرش دستباف سنندج',
    price: 17200000,
    category: 'دستباف',
    image: '/images/carpet28.jpg',
  },
  {
    id: 32,
    title: 'فرش فانتزی ساده طوسی',
    price: 4500000,
    category: 'مدرن',
    image: '/images/carpet29.jpg',
  },
  {
    id: 33,
    title: 'فرش ماشینی گلریز',
    price: 6950000,
    category: 'ماشینی',
    image: '/images/carpet30.jpg',
  },
];
