export const NavLinks = [
  {
    id: 1,
    name: 'صفحه اصلی',
    href: '/',
  },
  {
    id: 2,
    name: 'محصولات',
    href: '/products',
  },
  {
    id: 3,
    name: 'فرش های سه بعدی',
    href: '/3dmodels',
  },
  {
    id: 4,
    name: 'وبلاگ',
    href: '/blog',
  },
  {
    id: 5,
    name: 'تماس با ما',
    href: '/contactus',
  },
  {
    id: 6,
    name: 'درباره ما',
    href: '/about',
  },
];

export const models3D = [
  {
    title: 'فرش سه بعدی آبی',
    desc: 'با الهام از نقوش معرق کاشی‌کاری ایرانی، این فرش سه‌بعدی با رنگ‌های آرامش‌بخش فیروزه‌ای و طراحی متقارن، زیبایی خیره‌کننده‌ای به فضای شما می‌بخشد. مناسب سبک‌های مدرن و سنتی با نور ملایم.',
    price: 12500000,
    path: '/model1.glb',
  },
  {
    title: 'فرش سه‌ بعدی قرمز',
    desc: 'این فرش سه‌بعدی با طرح اصیل ترنج و زمینه‌ی قرمز غنی، نمادی از شکوه فرش‌های سنتی ایرانی است. جزئیات دقیق و بافت سه‌بعدی آن، جلوه‌ای زنده و واقعی به دکوراسیون شما می‌دهد.',
    price: 98000000,
    path: '/model2.glb',
  },
  {
    title: 'فرش سه ‌بعدی فیروزه ای',
    desc: 'طراحی این فرش با رنگ‌های محو و ظاهر کهنه‌نما، حس اصالت و خاطره را به فضای شما می‌آورد. مناسب فضاهای هنری، کافه‌ها، یا خانه‌هایی با حال‌و‌هوای نوستالژیک برای دکوراسیون شماست.',
    price: 15000000,
    path: '/model3.glb',
  },
];

export const ProductData = [
  {
    id: 1,
    image: '/slider1.webp',
    alt: 'picSlider1',
    title: 'فرش کهن دست بافت سهند زمینه سرمه ای',
    price: 23300000,
    delay: 0.3,
    quantity: 1,
    category: 'دستباف',
  },
  {
    id: 2,
    image: '/slider2.webp',
    alt: 'picSlider2',
    title: 'فرش دست بافت زانیس ماربل زمینه نوک مدادی',
    price: 49920000,
    delay: 0.6,
    quantity: 1,
    category: 'مدرن',
  },
  {
    id: 3,
    image: '/slider3.webp',
    alt: 'picSlider3',
    title: 'فرش دست بافت نگین مشهد زمینه فیلی رنگ',
    price: 14500000,
    delay: 0.9,
    quantity: 1,
    category: 'دستباف',
  },
  {
    id: 4,
    image: '/slider4.webp',
    alt: 'picSlider4',
    title: 'فرش دست بافت سهند آترینا زمینه سورمه ای',
    price: 23300000,
    delay: 1.2,
    quantity: 1,
    category: 'مدرن',
  },
  {
    id: 5,
    image: '/slider5.webp',
    alt: 'picSlider5',
    title: 'فرش ماشینی ماهساره طرح آترینا زمینه آبی',
    price: 13500000,
    delay: 0.3,
    quantity: 1,
    category: 'ابریشمی',
  },
  {
    id: 6,
    image: '/slider6.webp',
    alt: 'picSlider6',
    title: 'فرش ماشینی لوکس سهند زمینه سرمه ای ',
    price: 23300000,
    delay: 0.6,
    quantity: 1,
    category: 'ماشینی',
  },
  {
    id: 7,
    image: '/slider7.webp',
    alt: 'picSlider7',
    title: 'فرش ماشینی رادین طرح شاه عباسی زمینه کرم',
    price: 63030000,
    delay: 0.9,
    quantity: 1,
    category: 'مدرن',
  },
  {
    id: 8,
    image: '/slider8.webp',
    alt: 'picSlider8',
    title: 'فرش ماشینی مشهد طرح افشان زمینه کرم ',
    price: 11600000,
    delay: 1.2,
    quantity: 1,
    category: 'دستباف',
  },
  {
    id: 9,
    image: '/slider6.webp',
    alt: 'picSlider6',
    title: 'فرش ماشینی لوکس سهند زمینه سرمه ای ',
    price: 23300000,
    delay: 0.6,
    category: 'ماشینی',
  },
  {
    id: 10,
    image: '/slider9.webp',
    alt: 'picSlider9',
    title: 'فرش کهن  دست بافت سهند زمینه سرمه ای ',
    price: 24500000,
    delay: 0.6,
    category: 'ابریشمی',
  },
  {
    id: 11,
    image: '/slider7.webp',
    alt: 'picSlider7',
    title: 'فرش ماشینی رادین طرح شاه عباسی زمینه کرم',
    price: 63030000,
    delay: 0.9,
    category: 'دستباف',
  },
  {
    id: 12,
    image: '/slider8.webp',
    alt: 'picSlider8',
    title: 'فرش ماشینی مشهد طرح افشان زمینه کرم ',
    price: 11600000,
    delay: 1.2,
    category: 'مدرن',
  },
  {
    id: 13,
    image: '/slider10.webp',
    alt: 'picSlider10',
    title: 'فرش ماشینی ماهساره طرح آترینا زمینه فیروزه ای',
    price: 13500000,
    delay: 0.3,
    category: 'ماشینی',
  },
  {
    id: 14,
    title: 'فرش دستباف کاشان',
    price: 30000000,
    image: '/slider3.webp',
    quantity: 1,
    category: 'ابریشمی',
  },
  {
    id: 15,
    title: 'فرش فانتزی مدرن',
    price: 55000000,
    image: '/slider4.webp',
    quantity: 1,
    category: 'دستباف',
  },
  {
    id: 16,
    title: 'فرش کلاسیک 700 شانه',
    price: 64000000,
    image: '/slider5.webp',
    quantity: 1,
    category: 'مدرن',
  },
  {
    id: 17,
    title: 'فرش گل برجسته اصفهان',
    price: 98000000,
    image: '/slider6.webp',
    quantity: 1,
    category: 'دستباف',
  },
  {
    id: 18,
    title: 'فرش سنتی ترکمن',
    price: 45000000,
    image: '/slider7.webp',
    quantity: 1,
    category: 'ماشینی',
  },
  {
    id: 19,
    title: 'فرش فانتزی کودک',
    price: 39000000,
    image: '/slider8.webp',
    quantity: 1,
    category: 'ابریشمی',
  },
  {
    id: 20,
    title: 'فرش ماشینی ارزان',
    price: 27000000,
    image: '/slider9.webp',
    quantity: 1,
    category: 'مدرن',
  },
  {
    id: 21,
    title: 'فرش ابریشمی نایین',
    price: 48000000,
    image: '/images/carpet10.jpg',
    quantity: 1,
    category: 'دستباف',
  },
  {
    id: 22,
    title: 'فرش ماشینی گل برجسته',
    price: 91000000,
    category: 'ماشینی',
    image: '/images/carpet11.jpg',
    quantity: 1,
  },
  {
    id: 23,
    title: 'فرش دستباف مشهد',
    price: 75000000,
    category: 'دستباف',
    image: '/images/carpet12.jpg',
    quantity: 1,
  },
  {
    id: 24,
    title: 'فرش مدرن هندسی',
    price: 47000000,
    category: 'مدرن',
    image: '/images/carpet13.jpg',
    quantity: 1,
  },
  {
    id: 25,
    title: 'فرش ماشینی طرح افشان',
    price: 69000000,
    category: 'ماشینی',
    image: '/images/carpet14.jpg',
    quantity: 1,
  },
  {
    id: 26,
    title: 'فرش ابریشمی قم',
    price: 62000000,
    category: 'ابریشمی',
    image: '/images/carpet15.jpg',
    quantity: 1,
  },
  {
    id: 27,
    title: 'فرش دستباف تبریز اصیل',
    price: 10000000,
    category: 'دستباف',
    image: '/images/carpet16.jpg',
    quantity: 1,
  },
  {
    id: 28,
    title: 'فرش مدرن فانتزی رنگی',
    price: 52000000,
    category: 'مدرن',
    image: '/images/carpet17.jpg',
    quantity: 1,
  },
  {
    id: 29,
    title: 'فرش ماشینی ترک طرح جدید',
    price: 86000000,
    category: 'ماشینی',
    image: '/images/carpet18.jpg',
    quantity: 1,
  },
  {
    id: 30,
    title: 'فرش ابریشمی برجسته',
    price: 35000000,
    category: 'ابریشمی',
    image: '/images/carpet19.jpg',
    quantity: 1,
  },
  {
    id: 31,
    title: 'فرش دستباف بلوچ',
    price: 89000000,
    category: 'دستباف',
    image: '/images/carpet20.jpg',
    quantity: 1,
  },
  {
    id: 32,
    title: 'فرش کودک طرح خرس',
    price: 31000000,
    category: 'مدرن',
    image: '/images/carpet21.jpg',
    quantity: 1,
  },
  {
    id: 33,
    title: 'فرش ماشینی کلاسیک',
    price: 73000000,
    category: 'ماشینی',
    image: '/images/carpet22.jpg',
    quantity: 1,
  },
  {
    id: 34,
    title: 'فرش ابریشمی کاشان',
    price: 58000000,
    category: 'ابریشمی',
    image: '/images/carpet23.jpg',
    quantity: 1,
  },
  {
    id: 35,
    title: 'فرش دستباف هریس',
    price: 94000000,
    category: 'دستباف',
    image: '/images/carpet24.jpg',
    quantity: 1,
  },
  {
    id: 36,
    title: 'فرش مدرن مینیمال',
    price: 48000000,
    category: 'مدرن',
    image: '/images/carpet25.jpg',
    quantity: 1,
  },
  {
    id: 37,
    title: 'فرش ماشینی طرح خشتی',
    price: 78000000,
    category: 'ماشینی',
    image: '/images/carpet26.jpg',
    quantity: 1,
  },
  {
    id: 38,
    title: 'فرش ابریشمی گل ابریشم',
    price: 43000000,
    category: 'ابریشمی',
    image: '/images/carpet27.jpg',
    quantity: 1,
  },
  {
    id: 39,
    title: 'فرش دستباف سنندج',
    price: 72000000,
    category: 'دستباف',
    image: '/images/carpet28.jpg',
    quantity: 1,
  },
];

export let CountShoppingCart = 0;

export const BlogPosts = [
  {
    id: 1,
    title: 'چطور یک فرش دستباف واقعی و باارزش بخریم؟',
    excerpt:
      'همه فرش‌ها دستباف نیستند! با این راهنما یاد بگیر چطور بین هزار مدل، فرش اصیل ایرانی رو تشخیص بدی و با خیال راحت بخری.',
    image: '/blog1.webp',
    date: '۲ اردیبهشت ۱۴۰۴',
  },
  {
    id: 2,
    title: 'ماشینی یا دستباف؟ راهنمای انتخاب فرش برای خونه‌ات',
    excerpt:
      'بین فرش ماشینی شیک یا فرش دستباف اصیل مونده‌ای؟ این مقاله کمک‌ات می‌کنه دقیق و هوشمند انتخاب کنی؛ نه با شک و تردید!',
    image: '/blog2.webp',
    date: '۲۵ فروردین ۱۴۰۴',
  },
  {
    id: 3,
    title: '۵ راز مهم برای موندگاری و زیبایی فرش',
    excerpt:
      'با چند نکته ساده اما طلایی، عمر فرش‌ات رو چند برابر کن! این نکات رو فرش‌فروشی‌ها بهت نمی‌گن...',
    image: '/blog3.webp',
    date: '۱۸ فروردین ۱۴۰۴',
  },
];
